class Book {
  String? titel;
  String? price;
  String? image;
  String? discribtion;

  Book({required this.titel,
    required this.image,
    required this.discribtion,
    required this.price,
  });
}

class Catagory {
  List<Book> bookGrid;
  String photo;
  String name;

  Catagory({required this.name, required this.bookGrid,required this.photo});
}

List<Catagory> GridList() {
  List<Catagory> book = [];
  book.add( Catagory(name: 'تاريخ',
      photo: 'asset/تاريخ.jpg'
      ,
      bookGrid: [
        Book(titel: 'أيام العرب في الجاهليه',
            image: 'asset/download.jpg',
            discribtion: 'رواية عن احداث شبه الجزيرة قبل نزول الاسلام',
            price: '80ج'),
        Book(titel: 'فلسطين',
            image: 'asset/OIF.jpg',
            discribtion: 'تاريخ المقوامة ضد الاحتلال',
            price: '150ج'),
        Book(titel: 'المكتبة التاريخيه',
            image: 'asset/OIP.jpg',
            discribtion: 'حكايات التاريخ',
            price: '200ج'),
        Book(titel: 'تاريخ الحضارات للعام 1',
            image: 'asset/OIP (1).jpg',
            discribtion: 'التاريخ اليوناني',
            price: '75ج'),
        Book(titel: 'اساطير اليهود',
            image: 'asset/OIP (2).jpg',
            discribtion: 'بشاعة اليهود',
            price: '60'),
        Book(titel: 'اليهود في تاريخ الحضارات الاولي',
            image: 'asset/OIP (3).jpg',
            discribtion: ' ',
            price: '150ج'),
        Book(titel: 'يُحكي أن',
            image: 'asset/OIP (4).jpg',
            discribtion: 'قصص عبر العصور',
            price: '110ج'),
        Book(titel: 'تارخ ماقبل التاريخ',
            image: 'asset/OIP (5).jpg',
            discribtion: 'بداية اصوال العالم ومغمارت البشر',
            price: ''),
        Book(titel: 'المسلمون والحضارة الغربيه',
            image: 'asset/th.jpg',
            discribtion: 'تاثير العرب علي تاريخ الغرب والاندليس',
            price: '300ج'),



      ]),);
  book.add( Catagory(name: "علم نفس",
      photo: 'asset/IMG-20221214-WA0080.jpg',
      bookGrid: [
        Book(titel: 'أيام العرب في الجاهليه',
            image: 'asset/download.jpg',
            discribtion: 'رواية عن احداث شبه الجزيرة قبل نزول الاسلام',
            price: '80ج'),
        Book(titel: 'فلسطين',
            image: 'asset/OIF.jpg',
            discribtion: 'تاريخ المقوامة ضد الاحتلال',
            price: '150ج'),
        Book(titel: 'المكتبة التاريخيه',
            image: 'asset/OIP.jpg',
            discribtion: 'حكايات التاريخ',
            price: '200ج'),
        Book(titel: 'تاريخ الحضارات للعام 1',
            image: 'asset/OIP (1).jpg',
            discribtion: 'التاريخ اليوناني',
            price: '75ج'),
        Book(titel: 'اساطير اليهود',
            image: 'asset/OIP (2).jpg',
            discribtion: 'بشاعة اليهود',
            price: '60'),
        Book(titel: 'اليهود في تاريخ الحضارات الاولي',
            image: 'asset/OIP (3).jpg',
            discribtion: ' ',
            price: '150ج'),
        Book(titel: 'يُحكي أن',
            image: 'asset/OIP (4).jpg',
            discribtion: 'قصص عبر العصور',
            price: '110ج'),
        Book(titel: 'تارخ ماقبل التاريخ',
            image: 'asset/OIP (5).jpg',
            discribtion: 'بداية اصوال العالم ومغمارت البشر',
            price: ''),
        Book(titel: 'المسلمون والحضارة الغربيه',
            image: 'asset/th.jpg',
            discribtion: 'تاثير العرب علي تاريخ الغرب والاندليس',
            price: '300ج'),



      ]),);
  book.add( Catagory(name: "روايات",
      photo: 'asset/IMG-20221221-WA0070.jpg',
      bookGrid: [
        Book(titel: 'اسيرة ديسمبير',
            image: 'asset/ديسمبير.jpg',
            discribtion: '_',
            price: '80ج'),
        Book(titel: 'انس و شفق',
            image: 'asset/انس وشفق.jpg',
            discribtion: '_',
            price: '150ج'),
        Book(titel: 'الحب والنصيب',
            image: 'asset/الحب والنصيب.jpg',
            discribtion: '_',
            price: '200ج'),
        Book(titel: '14يوم يقدروا يفيدونا',
            image: 'asset/14يوم.jpg',
            discribtion: '_',
            price: '75ج'),
        Book(titel: 'اسيا',
            image: 'asset/اسيا.jpg',
            discribtion: '_',
            price: '60'),
        Book(titel: 'احببت اعمي',
            image: 'asset/احببت اعمي.jpg',
            discribtion: ' _',
            price: '150ج'),



      ]),);
  book.add( Catagory(name: 'فلسفة',
      photo: 'asset/IMG-20230123-WA0027.jpg'
      ,
      bookGrid: [
        Book(titel: 'أيام العرب في الجاهليه',
            image: 'asset/download.jpg',
            discribtion: 'رواية عن احداث شبه الجزيرة قبل نزول الاسلام',
            price: '80ج'),
        Book(titel: 'فلسطين',
            image: 'asset/OIF.jpg',
            discribtion: 'تاريخ المقوامة ضد الاحتلال',
            price: '150ج'),
        Book(titel: 'المكتبة التاريخيه',
            image: 'asset/OIP.jpg',
            discribtion: 'حكايات التاريخ',
            price: '200ج'),
        Book(titel: 'تاريخ الحضارات للعام 1',
            image: 'asset/OIP (1).jpg',
            discribtion: 'التاريخ اليوناني',
            price: '75ج'),
        Book(titel: 'اساطير اليهود',
            image: 'asset/OIP (2).jpg',
            discribtion: 'بشاعة اليهود',
            price: '60'),
        Book(titel: 'اليهود في تاريخ الحضارات الاولي',
            image: 'asset/OIP (3).jpg',
            discribtion: ' ',
            price: '150ج'),
        Book(titel: 'يُحكي أن',
            image: 'asset/OIP (4).jpg',
            discribtion: 'قصص عبر العصور',
            price: '110ج'),
        Book(titel: 'تارخ ماقبل التاريخ',
            image: 'asset/OIP (5).jpg',
            discribtion: 'بداية اصوال العالم ومغمارت البشر',
            price: ''),
        Book(titel: 'المسلمون والحضارة الغربيه',
            image: 'asset/th.jpg',
            discribtion: 'تاثير العرب علي تاريخ الغرب والاندليس',
            price: '300ج'),



      ]),);
  book.add( Catagory(name: "علوم",
      photo: 'asset/OIP (5).jpg',
      bookGrid: [
        Book(titel: 'أيام العرب في الجاهليه',
            image: 'asset/download.jpg',
            discribtion: 'رواية عن احداث شبه الجزيرة قبل نزول الاسلام',
            price: '80ج'),
        Book(titel: 'فلسطين',
            image: 'asset/OIF.jpg',
            discribtion: 'تاريخ المقوامة ضد الاحتلال',
            price: '150ج'),
        Book(titel: 'المكتبة التاريخيه',
            image: 'asset/OIP.jpg',
            discribtion: 'حكايات التاريخ',
            price: '200ج'),
        Book(titel: 'تاريخ الحضارات للعام 1',
            image: 'asset/OIP (1).jpg',
            discribtion: 'التاريخ اليوناني',
            price: '75ج'),
        Book(titel: 'اساطير اليهود',
            image: 'asset/OIP (2).jpg',
            discribtion: 'بشاعة اليهود',
            price: '60'),
        Book(titel: 'اليهود في تاريخ الحضارات الاولي',
            image: 'asset/OIP (3).jpg',
            discribtion: ' ',
            price: '150ج'),
        Book(titel: 'يُحكي أن',
            image: 'asset/OIP (4).jpg',
            discribtion: 'قصص عبر العصور',
            price: '110ج'),
        Book(titel: 'تارخ ماقبل التاريخ',
            image: 'asset/OIP (5).jpg',
            discribtion: 'بداية اصوال العالم ومغمارت البشر',
            price: ''),
        Book(titel: 'المسلمون والحضارة الغربيه',
            image: 'asset/th.jpg',
            discribtion: 'تاثير العرب علي تاريخ الغرب والاندليس',
            price: '300ج'),



      ]),);
  book.add( Catagory(name: "روايات",
      photo: 'asset/ديسمبير.jpg',
      bookGrid: [
        Book(titel: 'اسيرة ديسمبير',
            image: 'asset/ديسمبير.jpg',
            discribtion: '_',
            price: '80ج'),
        Book(titel: 'انس و شفق',
            image: 'asset/انس وشفق.jpg',
            discribtion: '_',
            price: '150ج'),
        Book(titel: 'الحب والنصيب',
            image: 'asset/الحب والنصيب.jpg',
            discribtion: '_',
            price: '200ج'),
        Book(titel: '14يوم يقدروا يفيدونا',
            image: 'asset/14يوم.jpg',
            discribtion: '_',
            price: '75ج'),
        Book(titel: 'اسيا',
            image: 'asset/اسيا.jpg',
            discribtion: '_',
            price: '60'),
        Book(titel: 'احببت اعمي',
            image: 'asset/احببت اعمي.jpg',
            discribtion: ' _',
            price: '150ج'),



      ]),);
  book.add( Catagory(name: 'تاريخ',
      photo: 'asset/download.jpg'
      ,
      bookGrid: [
        Book(titel: 'أيام العرب في الجاهليه',
            image: 'asset/download.jpg',
            discribtion: 'رواية عن احداث شبه الجزيرة قبل نزول الاسلام',
            price: '80ج'),
        Book(titel: 'فلسطين',
            image: 'asset/OIF.jpg',
            discribtion: 'تاريخ المقوامة ضد الاحتلال',
            price: '150ج'),
        Book(titel: 'المكتبة التاريخيه',
            image: 'asset/OIP.jpg',
            discribtion: 'حكايات التاريخ',
            price: '200ج'),
        Book(titel: 'تاريخ الحضارات للعام 1',
            image: 'asset/OIP (1).jpg',
            discribtion: 'التاريخ اليوناني',
            price: '75ج'),
        Book(titel: 'اساطير اليهود',
            image: 'asset/OIP (2).jpg',
            discribtion: 'بشاعة اليهود',
            price: '60'),
        Book(titel: 'اليهود في تاريخ الحضارات الاولي',
            image: 'asset/OIP (3).jpg',
            discribtion: ' ',
            price: '150ج'),
        Book(titel: 'يُحكي أن',
            image: 'asset/OIP (4).jpg',
            discribtion: 'قصص عبر العصور',
            price: '110ج'),
        Book(titel: 'تارخ ماقبل التاريخ',
            image: 'asset/OIP (5).jpg',
            discribtion: 'بداية اصوال العالم ومغمارت البشر',
            price: ''),
        Book(titel: 'المسلمون والحضارة الغربيه',
            image: 'asset/th.jpg',
            discribtion: 'تاثير العرب علي تاريخ الغرب والاندليس',
            price: '300ج'),



      ]),);
  book.add( Catagory(name: "علوم",
      photo: 'asset/OIP (5).jpg',
      bookGrid: [
        Book(titel: 'أيام العرب في الجاهليه',
            image: 'asset/download.jpg',
            discribtion: 'رواية عن احداث شبه الجزيرة قبل نزول الاسلام',
            price: '80ج'),
        Book(titel: 'فلسطين',
            image: 'asset/OIF.jpg',
            discribtion: 'تاريخ المقوامة ضد الاحتلال',
            price: '150ج'),
        Book(titel: 'المكتبة التاريخيه',
            image: 'asset/OIP.jpg',
            discribtion: 'حكايات التاريخ',
            price: '200ج'),
        Book(titel: 'تاريخ الحضارات للعام 1',
            image: 'asset/OIP (1).jpg',
            discribtion: 'التاريخ اليوناني',
            price: '75ج'),
        Book(titel: 'اساطير اليهود',
            image: 'asset/OIP (2).jpg',
            discribtion: 'بشاعة اليهود',
            price: '60'),
        Book(titel: 'اليهود في تاريخ الحضارات الاولي',
            image: 'asset/OIP (3).jpg',
            discribtion: ' ',
            price: '150ج'),
        Book(titel: 'يُحكي أن',
            image: 'asset/OIP (4).jpg',
            discribtion: 'قصص عبر العصور',
            price: '110ج'),
        Book(titel: 'تارخ ماقبل التاريخ',
            image: 'asset/OIP (5).jpg',
            discribtion: 'بداية اصوال العالم ومغمارت البشر',
            price: ''),
        Book(titel: 'المسلمون والحضارة الغربيه',
            image: 'asset/th.jpg',
            discribtion: 'تاثير العرب علي تاريخ الغرب والاندليس',
            price: '300ج'),



      ]),);
  book.add( Catagory(name: "روايات",
      photo: 'asset/ديسمبير.jpg',
      bookGrid: [
        Book(titel: 'اسيرة ديسمبير',
            image: 'asset/ديسمبير.jpg',
            discribtion: '_',
            price: '80ج'),
        Book(titel: 'انس و شفق',
            image: 'asset/انس وشفق.jpg',
            discribtion: '_',
            price: '150ج'),
        Book(titel: 'الحب والنصيب',
            image: 'asset/الحب والنصيب.jpg',
            discribtion: '_',
            price: '200ج'),
        Book(titel: '14يوم يقدروا يفيدونا',
            image: 'asset/14يوم.jpg',
            discribtion: '_',
            price: '75ج'),
        Book(titel: 'اسيا',
            image: 'asset/اسيا.jpg',
            discribtion: '_',
            price: '60'),
        Book(titel: 'احببت اعمي',
            image: 'asset/احببت اعمي.jpg',
            discribtion: ' _',
            price: '150ج'),



      ]),);
  book.add( Catagory(name: 'تاريخ',
      photo: 'asset/تاريخ.jpg'
      ,
      bookGrid: [
        Book(titel: 'أيام العرب في الجاهليه',
            image: 'asset/download.jpg',
            discribtion: 'رواية عن احداث شبه الجزيرة قبل نزول الاسلام',
            price: '80ج'),
        Book(titel: 'فلسطين',
            image: 'asset/OIF.jpg',
            discribtion: 'تاريخ المقوامة ضد الاحتلال',
            price: '150ج'),
        Book(titel: 'المكتبة التاريخيه',
            image: 'asset/OIP.jpg',
            discribtion: 'حكايات التاريخ',
            price: '200ج'),
        Book(titel: 'تاريخ الحضارات للعام 1',
            image: 'asset/OIP (1).jpg',
            discribtion: 'التاريخ اليوناني',
            price: '75ج'),
        Book(titel: 'اساطير اليهود',
            image: 'asset/OIP (2).jpg',
            discribtion: 'بشاعة اليهود',
            price: '60'),
        Book(titel: 'اليهود في تاريخ الحضارات الاولي',
            image: 'asset/OIP (3).jpg',
            discribtion: ' ',
            price: '150ج'),
        Book(titel: 'يُحكي أن',
            image: 'asset/OIP (4).jpg',
            discribtion: 'قصص عبر العصور',
            price: '110ج'),
        Book(titel: 'تارخ ماقبل التاريخ',
            image: 'asset/OIP (5).jpg',
            discribtion: 'بداية اصوال العالم ومغمارت البشر',
            price: ''),
        Book(titel: 'المسلمون والحضارة الغربيه',
            image: 'asset/th.jpg',
            discribtion: 'تاثير العرب علي تاريخ الغرب والاندليس',
            price: '300ج'),



      ]),);
  book.add( Catagory(name: "علوم",
      photo: 'asset/OIP (5).jpg',
      bookGrid: [
        Book(titel: 'أيام العرب في الجاهليه',
            image: 'asset/download.jpg',
            discribtion: 'رواية عن احداث شبه الجزيرة قبل نزول الاسلام',
            price: '80ج'),
        Book(titel: 'فلسطين',
            image: 'asset/OIF.jpg',
            discribtion: 'تاريخ المقوامة ضد الاحتلال',
            price: '150ج'),
        Book(titel: 'المكتبة التاريخيه',
            image: 'asset/OIP.jpg',
            discribtion: 'حكايات التاريخ',
            price: '200ج'),
        Book(titel: 'تاريخ الحضارات للعام 1',
            image: 'asset/OIP (1).jpg',
            discribtion: 'التاريخ اليوناني',
            price: '75ج'),
        Book(titel: 'اساطير اليهود',
            image: 'asset/OIP (2).jpg',
            discribtion: 'بشاعة اليهود',
            price: '60'),
        Book(titel: 'اليهود في تاريخ الحضارات الاولي',
            image: 'asset/OIP (3).jpg',
            discribtion: ' ',
            price: '150ج'),
        Book(titel: 'يُحكي أن',
            image: 'asset/OIP (4).jpg',
            discribtion: 'قصص عبر العصور',
            price: '110ج'),
        Book(titel: 'تارخ ماقبل التاريخ',
            image: 'asset/OIP (5).jpg',
            discribtion: 'بداية اصوال العالم ومغمارت البشر',
            price: ''),
        Book(titel: 'المسلمون والحضارة الغربيه',
            image: 'asset/th.jpg',
            discribtion: 'تاثير العرب علي تاريخ الغرب والاندليس',
            price: '300ج'),



      ]),);
  book.add( Catagory(name: "روايات",
      photo: 'asset/ديسمبير.jpg',
      bookGrid: [
        Book(titel: 'اسيرة ديسمبير',
            image: 'asset/ديسمبير.jpg',
            discribtion: '_',
            price: '80ج'),
        Book(titel: 'انس و شفق',
            image: 'asset/انس وشفق.jpg',
            discribtion: '_',
            price: '150ج'),
        Book(titel: 'الحب والنصيب',
            image: 'asset/الحب والنصيب.jpg',
            discribtion: '_',
            price: '200ج'),
        Book(titel: '14يوم يقدروا يفيدونا',
            image: 'asset/14يوم.jpg',
            discribtion: '_',
            price: '75ج'),
        Book(titel: 'اسيا',
            image: 'asset/اسيا.jpg',
            discribtion: '_',
            price: '60'),
        Book(titel: 'احببت اعمي',
            image: 'asset/احببت اعمي.jpg',
            discribtion: ' _',
            price: '150ج'),



      ]),);
  book.add( Catagory(name: 'تاريخ',
      photo: 'asset/تاريخ.jpg'
      ,
      bookGrid: [
        Book(titel: 'أيام العرب في الجاهليه',
            image: 'asset/download.jpg',
            discribtion: 'رواية عن احداث شبه الجزيرة قبل نزول الاسلام',
            price: '80ج'),
        Book(titel: 'فلسطين',
            image: 'asset/OIF.jpg',
            discribtion: 'تاريخ المقوامة ضد الاحتلال',
            price: '150ج'),
        Book(titel: 'المكتبة التاريخيه',
            image: 'asset/OIP.jpg',
            discribtion: 'حكايات التاريخ',
            price: '200ج'),
        Book(titel: 'تاريخ الحضارات للعام 1',
            image: 'asset/OIP (1).jpg',
            discribtion: 'التاريخ اليوناني',
            price: '75ج'),
        Book(titel: 'اساطير اليهود',
            image: 'asset/OIP (2).jpg',
            discribtion: 'بشاعة اليهود',
            price: '60'),
        Book(titel: 'اليهود في تاريخ الحضارات الاولي',
            image: 'asset/OIP (3).jpg',
            discribtion: ' ',
            price: '150ج'),
        Book(titel: 'يُحكي أن',
            image: 'asset/OIP (4).jpg',
            discribtion: 'قصص عبر العصور',
            price: '110ج'),
        Book(titel: 'تارخ ماقبل التاريخ',
            image: 'asset/OIP (5).jpg',
            discribtion: 'بداية اصوال العالم ومغمارت البشر',
            price: ''),
        Book(titel: 'المسلمون والحضارة الغربيه',
            image: 'asset/th.jpg',
            discribtion: 'تاثير العرب علي تاريخ الغرب والاندليس',
            price: '300ج'),



      ]),);

  book.add( Catagory(name: "روايات",
      photo: 'asset/ديسمبير.jpg',
      bookGrid: [
        Book(titel: 'اسيرة ديسمبير',
            image: 'asset/ديسمبير.jpg',
            discribtion: '_',
            price: '80ج'),
        Book(titel: 'انس و شفق',
            image: 'asset/انس وشفق.jpg',
            discribtion: '_',
            price: '150ج'),
        Book(titel: 'الحب والنصيب',
            image: 'asset/الحب والنصيب.jpg',
            discribtion: '_',
            price: '200ج'),
        Book(titel: '14يوم يقدروا يفيدونا',
            image: 'asset/14يوم.jpg',
            discribtion: '_',
            price: '75ج'),
        Book(titel: 'اسيا',
            image: 'asset/اسيا.jpg',
            discribtion: '_',
            price: '60'),
        Book(titel: 'احببت اعمي',
            image: 'asset/احببت اعمي.jpg',
            discribtion: ' _',
            price: '150ج'),



      ]),);
  return book;
}
